project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "blogs/*.qmd"
    - "projects/*.qmd"
    - "projects/project1/*.qmd"
    - "projects/project2/*.qmd"
    - "projects_jp/project1/*.qmd"
    - "projects_jp/project2/*.qmd"
    - "!posts_bak/"

website:
  title: "Leia Kawamura"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blogs

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-after-body: lang-switch.html
