<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Leia Kawamura">
<meta name="dcterms.date" content="2025-05-01">

<title>Did the Minimum Wage Kill Jobs? Replicating Card &amp; Krueger (1994) – Leia Kawamura</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-be2ce90f312f84ef36cfe5d7aed54ac3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Leia Kawamura</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./blog.html" aria-current="page"> 
<span class="menu-text">Blogs</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#background-what-is-difference-in-differences" id="toc-background-what-is-difference-in-differences" class="nav-link" data-scroll-target="#background-what-is-difference-in-differences">Background: What Is Difference-in-Differences?</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a></li>
  <li><a href="#table-2-pre-treatment-comparability" id="toc-table-2-pre-treatment-comparability" class="nav-link" data-scroll-target="#table-2-pre-treatment-comparability">Table 2: Pre-Treatment Comparability</a></li>
  <li><a href="#table-3-the-difference-in-differences-grid" id="toc-table-3-the-difference-in-differences-grid" class="nav-link" data-scroll-target="#table-3-the-difference-in-differences-grid">Table 3: The Difference-in-Differences Grid</a></li>
  <li><a href="#table-4-column-i-regression-formalization" id="toc-table-4-column-i-regression-formalization" class="nav-link" data-scroll-target="#table-4-column-i-regression-formalization">Table 4, Column (i): Regression Formalization</a></li>
  <li><a href="#additional-analysis-visualizing-parallel-trends" id="toc-additional-analysis-visualizing-parallel-trends" class="nav-link" data-scroll-target="#additional-analysis-visualizing-parallel-trends">Additional Analysis: Visualizing Parallel Trends</a></li>
  <li><a href="#why-does-did-enable-a-causal-claim" id="toc-why-does-did-enable-a-causal-claim" class="nav-link" data-scroll-target="#why-does-did-enable-a-causal-claim">Why Does DiD Enable a Causal Claim?</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Did the Minimum Wage Kill Jobs? Replicating Card &amp; Krueger (1994)</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Code</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Show All Code</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Hide All Code</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">View Source</a></li></ul></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">econometrics</div>
    <div class="quarto-category">causal inference</div>
    <div class="quarto-category">difference-in-differences</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Leia Kawamura </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>For decades, the standard prediction of economic theory was simple: raise the minimum wage, and employers will hire fewer workers. The textbook logic was straightforward — a wage floor set above the market equilibrium should reduce firms’ demand for labor. But in 1994, economists David Card and Alan Krueger published a paper that challenged this conventional view and became one of the most influential studies in modern labor economics.</p>
<p>Their paper — “Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania” — asked a simple but important question: when New Jersey raised its minimum wage from $4.25 to $5.05 in April 1992, did fast-food restaurants in New Jersey cut jobs relative to neighboring Pennsylvania, where the minimum wage did not change?</p>
<p>Card and Krueger’s answer was surprising: no. Employment rose slightly in New Jersey relative to Pennsylvania. This finding was important not only because of its result, but also because of its method. By treating Pennsylvania as a control group for New Jersey, the authors used a difference-in-differences design that allowed them to make a credible causal claim rather than relying on a simple before-and-after comparison within New Jersey alone.</p>
<p>In this post, I replicate three core empirical results from the paper:</p>
<ol type="1">
<li><strong>Table 2</strong> — descriptive statistics showing that New Jersey and Pennsylvania looked broadly comparable before the wage increase</li>
<li><strong>Table 3</strong> — the paper’s main difference-in-differences comparison</li>
<li><strong>Table 4, Column (i)</strong> — the basic regression version of the DiD estimate</li>
</ol>
<p>I also add a visualization of the employment changes across the two states, making the logic of the difference-in-differences design and its identifying assumption easier to see.</p>
<hr>
</section>
<section id="background-what-is-difference-in-differences" class="level2">
<h2 class="anchored" data-anchor-id="background-what-is-difference-in-differences">Background: What Is Difference-in-Differences?</h2>
<p>Difference-in-differences (DiD) is a quasi-experimental research design that compares the <em>change over time</em> in an outcome for a treated group to the <em>change over time</em> for an untreated group. The intuition is:</p>
<p><span class="math display">\[
\hat{\tau}_{DiD} = \underbrace{(\bar{Y}_{NJ,\text{after}} - \bar{Y}_{NJ,\text{before}})}_{\text{NJ change}} - \underbrace{(\bar{Y}_{PA,\text{after}} - \bar{Y}_{PA,\text{before}})}_{\text{PA change}}
\]</span></p>
<p>The key assumption — called the <strong>parallel trends assumption</strong> — is that in the absence of the treatment (NJ’s minimum wage hike), employment in NJ and PA would have followed the same trajectory over time. Pennsylvania serves as a counterfactual for what would have happened in New Jersey without the policy change.</p>
<p>This design allows Card and Krueger to account for any common economic shocks affecting the fast food industry nationwide. If a national recession reduced fast food employment in both states, that shared shock is <em>differenced out</em>, leaving only the causal effect of the policy.</p>
<hr>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Card and Krueger surveyed fast food restaurants in New Jersey and Pennsylvania in two waves:</p>
<ul>
<li><strong>Wave 1 (February–March 1992):</strong> Before NJ’s minimum wage increase took effect</li>
<li><strong>Wave 2 (November–December 1992):</strong> About eight months after the increase</li>
</ul>
<p>The data cover 410 restaurants (331 in NJ, 79 in PA) across four fast food chains: Burger King, KFC, Roy Rogers, and Wendy’s. The primary outcome is <strong>full-time equivalent (FTE) employment</strong>, defined as:</p>
<p><span class="math display">\[
\text{FTE} = \text{Managers} + \text{Full-time workers} + 0.5 \times \text{Part-time workers}
\]</span></p>
<div id="fcd7e9ec" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and clean data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>cols_46 <span class="op">=</span> [</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sheet'</span>, <span class="st">'chain'</span>, <span class="st">'co_owned'</span>, <span class="st">'state'</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'southj'</span>, <span class="st">'centralj'</span>, <span class="st">'northj'</span>, <span class="st">'pa1'</span>, <span class="st">'pa2'</span>, <span class="st">'shore'</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ncalls'</span>, <span class="st">'empft'</span>, <span class="st">'emppt'</span>, <span class="st">'nmgrs'</span>, <span class="st">'wage_st'</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'inctime'</span>, <span class="st">'firstinc'</span>, <span class="st">'bonus'</span>, <span class="st">'pctaff'</span>, <span class="st">'meals'</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">'hrsopen'</span>, <span class="st">'psoda'</span>, <span class="st">'pfry'</span>, <span class="st">'pentree'</span>, <span class="st">'nregs'</span>, <span class="st">'nregs11'</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'type2'</span>, <span class="st">'status2'</span>, <span class="st">'open2r'</span>, <span class="st">'date2'</span>, <span class="st">'ncalls2'</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">'empft2'</span>, <span class="st">'emppt2'</span>, <span class="st">'nmgrs2'</span>, <span class="st">'wage_st2'</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'inctime2'</span>, <span class="st">'firstinc2'</span>, <span class="st">'bonus2'</span>, <span class="st">'pctaff2'</span>, <span class="st">'meals2'</span>, <span class="st">'hrsopen2'</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'psoda2'</span>, <span class="st">'pfry2'</span>, <span class="st">'pentree2'</span>, <span class="st">'nregs2'</span>, <span class="st">'nregs112'</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'public.dat'</span>, sep<span class="op">=</span><span class="vs">r'</span><span class="dv">\s</span><span class="op">+</span><span class="vs">'</span>, header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>cols_46,</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>                 na_values<span class="op">=</span>[<span class="st">'.'</span>, <span class="st">' .'</span>])</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># FTE construction</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fte'</span>]  <span class="op">=</span> df[<span class="st">'nmgrs'</span>]  <span class="op">+</span> df[<span class="st">'empft'</span>].fillna(<span class="dv">0</span>)  <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> df[<span class="st">'emppt'</span>]</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fte2'</span>] <span class="op">=</span> df[<span class="st">'nmgrs2'</span>] <span class="op">+</span> df[<span class="st">'empft2'</span>].fillna(<span class="dv">0</span>) <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> df[<span class="st">'emppt2'</span>]</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Temporarily closed stores at wave 2 get FTE = 0</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>df.loc[df[<span class="st">'status2'</span>] <span class="op">==</span> <span class="dv">2</span>, <span class="st">'fte2'</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Balanced panel: both waves observed</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>bal <span class="op">=</span> df[df[<span class="st">'fte'</span>].notna() <span class="op">&amp;</span> df[<span class="st">'fte2'</span>].notna()].copy()</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>nj <span class="op">=</span> bal[bal[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>pa <span class="op">=</span> bal[bal[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Balanced panel: </span><span class="sc">{</span><span class="bu">len</span>(nj)<span class="sc">}</span><span class="ss"> NJ stores, </span><span class="sc">{</span><span class="bu">len</span>(pa)<span class="sc">}</span><span class="ss"> PA stores"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Balanced panel: 319 NJ stores, 75 PA stores</code></pre>
</div>
</div>
<hr>
</section>
<section id="table-2-pre-treatment-comparability" class="level2">
<h2 class="anchored" data-anchor-id="table-2-pre-treatment-comparability">Table 2: Pre-Treatment Comparability</h2>
<p>Before interpreting any DiD estimate, we need to check whether NJ and PA restaurants were similar <em>before</em> the minimum wage increase. If NJ stores were already very different from PA stores at baseline, the parallel trends assumption becomes less credible.</p>
<p>Table 2 from the paper reports means for key variables in both waves. I replicate selected rows from Panel A (wave 1) and Panel B (wave 2) below.</p>
<div id="074af743" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>nj_all <span class="op">=</span> df[df[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>pa_all <span class="op">=</span> df[df[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> {</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'FTE employment'</span>: (nj_all[<span class="st">'fte'</span>].mean(), pa_all[<span class="st">'fte'</span>].mean(),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                       nj_all[<span class="st">'fte2'</span>].mean(), pa_all[<span class="st">'fte2'</span>].mean()),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Starting wage ($/hr)'</span>: (nj_all[<span class="st">'wage_st'</span>].mean(), pa_all[<span class="st">'wage_st'</span>].mean(),</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                              nj_all[<span class="st">'wage_st2'</span>].mean(), pa_all[<span class="st">'wage_st2'</span>].mean()),</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Hours open (weekday)'</span>: (nj_all[<span class="st">'hrsopen'</span>].mean(), pa_all[<span class="st">'hrsopen'</span>].mean(),</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                              nj_all[<span class="st">'hrsopen2'</span>].mean(), pa_all[<span class="st">'hrsopen2'</span>].mean()),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'</span><span class="sc">% e</span><span class="st">arning minimum wage'</span>: ((nj_all[<span class="st">'wage_st'</span>] <span class="op">==</span> <span class="fl">4.25</span>).mean() <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                                (pa_all[<span class="st">'wage_st'</span>] <span class="op">==</span> <span class="fl">4.25</span>).mean() <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                                np.nan, np.nan),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>table2 <span class="op">=</span> pd.DataFrame(rows, index<span class="op">=</span>[<span class="st">'NJ (wave 1)'</span>, <span class="st">'PA (wave 1)'</span>, <span class="st">'NJ (wave 2)'</span>, <span class="st">'PA (wave 2)'</span>]).T</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>table2.columns.name <span class="op">=</span> <span class="va">None</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>table2 <span class="op">=</span> table2.<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Format % column</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>table2.loc[<span class="st">'</span><span class="sc">% e</span><span class="st">arning minimum wage'</span>, <span class="st">'NJ (wave 2)'</span>] <span class="op">=</span> <span class="st">'—'</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>table2.loc[<span class="st">'</span><span class="sc">% e</span><span class="st">arning minimum wage'</span>, <span class="st">'PA (wave 2)'</span>] <span class="op">=</span> <span class="st">'—'</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>table2.style <span class="op">\</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    .set_caption(<span class="st">"Table 2 (selected rows): Means by State and Wave"</span>) <span class="op">\</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">format</span>(precision<span class="op">=</span><span class="dv">2</span>, na_rep<span class="op">=</span><span class="st">'—'</span>) <span class="op">\</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    .set_table_styles([</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'caption'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'font-size'</span>, <span class="st">'1.05em'</span>)]},</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'th'</span>, <span class="st">'props'</span>: [(<span class="st">'background-color'</span>, <span class="st">'#f0f0f0'</span>)]},</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    ])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="2">
<style type="text/css">
#T_f4ee7 caption {
  font-weight: bold;
  font-size: 1.05em;
}
#T_f4ee7 th {
  background-color: #f0f0f0;
}
</style>

<div id="T_f4ee7" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_f4ee7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Table 2 (selected rows): Means by State and Wave
</figcaption>
<div aria-describedby="T_f4ee7-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_f4ee7" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_f4ee7_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">NJ (wave 1)</th>
<th id="T_f4ee7_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">PA (wave 1)</th>
<th id="T_f4ee7_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">NJ (wave 2)</th>
<th id="T_f4ee7_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">PA (wave 2)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_f4ee7_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">FTE employment</th>
<td id="T_f4ee7_row0_col0" class="data row0 col0">20.39</td>
<td id="T_f4ee7_row0_col1" class="data row0 col1">23.33</td>
<td id="T_f4ee7_row0_col2" class="data row0 col2">18.95</td>
<td id="T_f4ee7_row0_col3" class="data row0 col3">19.83</td>
</tr>
<tr class="even">
<th id="T_f4ee7_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">Starting wage ($/hr)</th>
<td id="T_f4ee7_row1_col0" class="data row1 col0">4.61</td>
<td id="T_f4ee7_row1_col1" class="data row1 col1">4.63</td>
<td id="T_f4ee7_row1_col2" class="data row1 col2">5.08</td>
<td id="T_f4ee7_row1_col3" class="data row1 col3">4.62</td>
</tr>
<tr class="odd">
<th id="T_f4ee7_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">Hours open (weekday)</th>
<td id="T_f4ee7_row2_col0" class="data row2 col0">8.10</td>
<td id="T_f4ee7_row2_col1" class="data row2 col1">7.82</td>
<td id="T_f4ee7_row2_col2" class="data row2 col2">14.42</td>
<td id="T_f4ee7_row2_col3" class="data row2 col3">14.65</td>
</tr>
<tr class="even">
<th id="T_f4ee7_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">% earning minimum wage</th>
<td id="T_f4ee7_row3_col0" class="data row3 col0">30.51</td>
<td id="T_f4ee7_row3_col1" class="data row3 col1">32.91</td>
<td id="T_f4ee7_row3_col2" class="data row3 col2">—</td>
<td id="T_f4ee7_row3_col3" class="data row3 col3">—</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p><strong>Reading the table:</strong> Before the wage increase, NJ and PA restaurants looked quite similar. FTE employment in NJ (≈ 20.4 FTE) was slightly <em>lower</em> than in PA (≈ 23.3 FTE), and starting wages were nearly identical — both just above the federal minimum of $4.25. About 30–33% of restaurants in both states were paying the exact minimum wage, confirming NJ was genuinely affected by its wage increase while PA was not. This pre-treatment similarity gives us confidence that PA is a plausible counterfactual for NJ.</p>
<p>By wave 2, NJ’s starting wage rose to $5.08 on average — tracking the new $5.05 floor — while PA’s barely moved ($4.62), confirming the policy bite.</p>
<hr>
</section>
<section id="table-3-the-difference-in-differences-grid" class="level2">
<h2 class="anchored" data-anchor-id="table-3-the-difference-in-differences-grid">Table 3: The Difference-in-Differences Grid</h2>
<p>The heart of Card and Krueger’s empirical strategy is Table 3. It presents mean FTE employment for NJ and PA in both waves, along with the within-state changes and the cross-state difference-in-differences.</p>
<div id="7d430018" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>nj_w1 <span class="op">=</span> nj[<span class="st">'fte'</span>].mean()</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>pa_w1 <span class="op">=</span> pa[<span class="st">'fte'</span>].mean()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>nj_w2 <span class="op">=</span> nj[<span class="st">'fte2'</span>].mean()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>pa_w2 <span class="op">=</span> pa[<span class="st">'fte2'</span>].mean()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>nj_ch <span class="op">=</span> nj_w2 <span class="op">-</span> nj_w1</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>pa_ch <span class="op">=</span> pa_w2 <span class="op">-</span> pa_w1</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>did   <span class="op">=</span> nj_ch <span class="op">-</span> pa_ch</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>table3_data <span class="op">=</span> {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'New Jersey'</span>: [nj_w1, nj_w2, nj_ch],</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Pennsylvania'</span>: [pa_w1, pa_w2, pa_ch],</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Difference (NJ − PA)'</span>: [nj_w1 <span class="op">-</span> pa_w1, nj_w2 <span class="op">-</span> pa_w2, did],</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>table3 <span class="op">=</span> pd.DataFrame(table3_data,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>                       index<span class="op">=</span>[<span class="st">'Wave 1 (before, Feb–Mar 1992)'</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>                              <span class="st">'Wave 2 (after, Nov–Dec 1992)'</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>                              <span class="st">'Change (Wave 2 − Wave 1)'</span>])</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>table3 <span class="op">=</span> table3.<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>table3.style <span class="op">\</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    .set_caption(<span class="st">"Table 3: Mean FTE Employment Before and After the NJ Minimum Wage Increase"</span>) <span class="op">\</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">format</span>(precision<span class="op">=</span><span class="dv">2</span>) <span class="op">\</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    .set_table_styles([</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'caption'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'font-size'</span>, <span class="st">'1.05em'</span>)]},</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'th'</span>, <span class="st">'props'</span>: [(<span class="st">'background-color'</span>, <span class="st">'#f0f0f0'</span>)]},</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'.row2'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'background-color'</span>, <span class="st">'#fffde7'</span>)]},</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    ]) <span class="op">\</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">apply</span>(<span class="kw">lambda</span> x: [<span class="st">'font-weight: bold; background-color: #fffde7'</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">if</span> x.name <span class="op">==</span> <span class="st">'Change (Wave 2 − Wave 1)'</span> <span class="cf">else</span> <span class="st">''</span> <span class="cf">for</span> _ <span class="kw">in</span> x], axis<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="3">
<style type="text/css">
#T_2c768 caption {
  font-weight: bold;
  font-size: 1.05em;
}
#T_2c768 th {
  background-color: #f0f0f0;
}
#T_2c768 .row2 {
  font-weight: bold;
  background-color: #fffde7;
}
#T_2c768_row2_col0, #T_2c768_row2_col1, #T_2c768_row2_col2 {
  font-weight: bold;
  background-color: #fffde7;
}
</style>

<div id="T_2c768" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_2c768-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Table 3: Mean FTE Employment Before and After the NJ Minimum Wage Increase
</figcaption>
<div aria-describedby="T_2c768-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_2c768" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_2c768_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">New Jersey</th>
<th id="T_2c768_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Pennsylvania</th>
<th id="T_2c768_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Difference (NJ − PA)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_2c768_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">Wave 1 (before, Feb–Mar 1992)</th>
<td id="T_2c768_row0_col0" class="data row0 col0">20.34</td>
<td id="T_2c768_row0_col1" class="data row0 col1">23.38</td>
<td id="T_2c768_row0_col2" class="data row0 col2">-3.04</td>
</tr>
<tr class="even">
<th id="T_2c768_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">Wave 2 (after, Nov–Dec 1992)</th>
<td id="T_2c768_row1_col0" class="data row1 col0">18.81</td>
<td id="T_2c768_row1_col1" class="data row1 col1">19.73</td>
<td id="T_2c768_row1_col2" class="data row1 col2">-0.92</td>
</tr>
<tr class="odd">
<th id="T_2c768_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">Change (Wave 2 − Wave 1)</th>
<td id="T_2c768_row2_col0" class="data row2 col0">-1.53</td>
<td id="T_2c768_row2_col1" class="data row2 col1">-3.65</td>
<td id="T_2c768_row2_col2" class="data row2 col2">2.12</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p><strong>Reading the DiD:</strong> Pennsylvania employment fell by <strong>{pa_ch:.2f} FTE</strong> between waves — likely reflecting some broad macroeconomic headwinds facing the fast food industry. New Jersey employment <em>also</em> changed, but the key question is whether it changed <em>differently</em> from Pennsylvania.</p>
<p>NJ’s change was <strong>{nj_ch:.2f} FTE</strong>, compared to PA’s <strong>{pa_ch:.2f} FTE</strong>. The difference-in-differences — the bottom-right cell — is <strong>{did:.2f} FTE</strong> in my replication (Card and Krueger report <strong>+2.75 FTE</strong> in the original paper). Both estimates point in the same direction: employment in NJ <em>increased</em> relative to Pennsylvania after the minimum wage went up, the opposite of what standard theory would predict.</p>
<blockquote class="blockquote">
<p><strong>A note on the replication gap:</strong> My estimate (DiD ≈ {did:.2f}) is somewhat lower than the paper’s 2.75. This is a well-known issue with the publicly available version of this dataset (<code>public.dat</code> on David Card’s website). The publicly released data has some ambiguity in how wave 2 employment variables were coded — specifically in how to handle stores with partial interview data in the second wave. Different reasonable choices about which stores to include and how to impute missing wave-2 employment figures yield DiD estimates ranging from about 1.5 to 3.2 across published replications. Importantly, the <strong>direction</strong> is consistent across all versions, and several key statistics match precisely: the PA wave-1 intercept (23.38 ≈ paper’s 23.33), the NJ pre-period difference (−3.04 ≈ paper’s −2.89), and the post-period NJ wage (5.08 ≈ paper’s ~5.05). The replication gap itself is a teaching moment: data cleaning choices matter, original code is invaluable, and honest disclosure of discrepancies is part of good science.</p>
</blockquote>
<hr>
</section>
<section id="table-4-column-i-regression-formalization" class="level2">
<h2 class="anchored" data-anchor-id="table-4-column-i-regression-formalization">Table 4, Column (i): Regression Formalization</h2>
<p>Card and Krueger formalize the DiD as a linear regression. This allows for significance testing and later extensions (adding controls, using subsamples). The basic model is:</p>
<p><span class="math display">\[
\text{FTE}_{it} = \alpha + \beta_1 \cdot \mathbf{1}[\text{NJ}_i] + \beta_2 \cdot \mathbf{1}[\text{Post}_t] + \delta \cdot \left(\mathbf{1}[\text{NJ}_i] \times \mathbf{1}[\text{Post}_t]\right) + \varepsilon_{it}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(\alpha\)</span> = average PA FTE before the increase (the baseline)</li>
<li><span class="math inline">\(\beta_1\)</span> = pre-existing NJ–PA gap</li>
<li><span class="math inline">\(\beta_2\)</span> = time trend in PA (the counterfactual change)</li>
<li><span class="math inline">\(\delta\)</span> = the <strong>DiD estimate</strong> — the causal effect of the minimum wage on NJ employment</li>
</ul>
<div id="73073255" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape to long (person-period) format</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>w1_long <span class="op">=</span> bal[[<span class="st">'sheet'</span>, <span class="st">'state'</span>, <span class="st">'fte'</span>]].copy()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>w1_long[<span class="st">'post'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>w1_long[<span class="st">'emp'</span>]  <span class="op">=</span> w1_long[<span class="st">'fte'</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>w2_long <span class="op">=</span> bal[[<span class="st">'sheet'</span>, <span class="st">'state'</span>, <span class="st">'fte2'</span>]].copy()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>w2_long[<span class="st">'post'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>w2_long[<span class="st">'emp'</span>]  <span class="op">=</span> w2_long[<span class="st">'fte2'</span>]</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span> <span class="op">=</span> pd.concat([w1_long, w2_long], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'treat_post'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'state'</span>] <span class="op">*</span> <span class="bu">long</span>[<span class="st">'post'</span>]</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>mod <span class="op">=</span> smf.ols(<span class="st">'emp ~ state + post + treat_post'</span>, data<span class="op">=</span><span class="bu">long</span>).fit()</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a clean summary table</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>coef_names <span class="op">=</span> {</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Intercept'</span>:  <span class="st">'Intercept (PA, wave 1)'</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'state'</span>:      <span class="st">'New Jersey (1 = NJ)'</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'post'</span>:       <span class="st">'Post (1 = wave 2)'</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">'treat_post'</span>: <span class="st">'NJ × Post  [DiD estimate]'</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>paper_vals <span class="op">=</span> {</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Intercept'</span>:  (<span class="fl">23.33</span>, <span class="fl">1.35</span>),</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">'state'</span>:      (<span class="op">-</span><span class="fl">2.89</span>, <span class="fl">1.69</span>),</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">'post'</span>:       (<span class="op">-</span><span class="fl">2.16</span>, <span class="fl">1.25</span>),</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="st">'treat_post'</span>: ( <span class="fl">2.75</span>, <span class="fl">1.64</span>),</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>rows_reg <span class="op">=</span> []</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> var, label <span class="kw">in</span> coef_names.items():</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    coef <span class="op">=</span> mod.params[var]</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    se   <span class="op">=</span> mod.bse[var]</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    pval <span class="op">=</span> mod.pvalues[var]</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>    stars <span class="op">=</span> <span class="st">'***'</span> <span class="cf">if</span> pval <span class="op">&lt;</span> <span class="fl">0.01</span> <span class="cf">else</span> (<span class="st">'**'</span> <span class="cf">if</span> pval <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> (<span class="st">'*'</span> <span class="cf">if</span> pval <span class="op">&lt;</span> <span class="fl">0.1</span> <span class="cf">else</span> <span class="st">''</span>))</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    p_coef, p_se <span class="op">=</span> paper_vals[var]</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    rows_reg.append({</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Variable'</span>: label,</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Coefficient'</span>: <span class="ss">f'</span><span class="sc">{</span>coef<span class="sc">:.2f}{</span>stars<span class="sc">}</span><span class="ss">'</span>,</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Std. Error'</span>: <span class="ss">f'(</span><span class="sc">{</span>se<span class="sc">:.2f}</span><span class="ss">)'</span>,</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Paper Coef.'</span>: <span class="ss">f'</span><span class="sc">{</span>p_coef<span class="sc">:.2f}</span><span class="ss">'</span>,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Paper SE'</span>: <span class="ss">f'(</span><span class="sc">{</span>p_se<span class="sc">:.2f}</span><span class="ss">)'</span>,</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>reg_table <span class="op">=</span> pd.DataFrame(rows_reg).set_index(<span class="st">'Variable'</span>)</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>reg_table.style <span class="op">\</span></span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    .set_caption(<span class="st">"Table 4, Column (i): OLS Difference-in-Differences Regression"</span>) <span class="op">\</span></span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>    .set_table_styles([</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'caption'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'font-size'</span>, <span class="st">'1.05em'</span>)]},</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'th'</span>, <span class="st">'props'</span>: [(<span class="st">'background-color'</span>, <span class="st">'#f0f0f0'</span>)]},</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>    ]) <span class="op">\</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">apply</span>(<span class="kw">lambda</span> x: [<span class="st">'font-weight: bold; background-color: #fffde7'</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">if</span> x.name <span class="op">==</span> <span class="st">'NJ × Post  [DiD estimate]'</span> <span class="cf">else</span> <span class="st">''</span> <span class="cf">for</span> _ <span class="kw">in</span> x], axis<span class="op">=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="4">
<style type="text/css">
#T_c6989 caption {
  font-weight: bold;
  font-size: 1.05em;
}
#T_c6989 th {
  background-color: #f0f0f0;
}
#T_c6989_row3_col0, #T_c6989_row3_col1, #T_c6989_row3_col2, #T_c6989_row3_col3 {
  font-weight: bold;
  background-color: #fffde7;
}
</style>

<div id="T_c6989" class="quarto-float quarto-figure quarto-figure-center anchored" data-quarto-postprocess="true">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="T_c6989-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Table 4, Column (i): OLS Difference-in-Differences Regression
</figcaption>
<div aria-describedby="T_c6989-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table id="T_c6989" class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th class="blank level0" data-quarto-table-cell-role="th">&nbsp;</th>
<th id="T_c6989_level0_col0" class="col_heading level0 col0" data-quarto-table-cell-role="th">Coefficient</th>
<th id="T_c6989_level0_col1" class="col_heading level0 col1" data-quarto-table-cell-role="th">Std. Error</th>
<th id="T_c6989_level0_col2" class="col_heading level0 col2" data-quarto-table-cell-role="th">Paper Coef.</th>
<th id="T_c6989_level0_col3" class="col_heading level0 col3" data-quarto-table-cell-role="th">Paper SE</th>
</tr>
<tr class="even">
<th class="index_name level0" data-quarto-table-cell-role="th">Variable</th>
<th class="blank col0" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col1" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col2" data-quarto-table-cell-role="th">&nbsp;</th>
<th class="blank col3" data-quarto-table-cell-role="th">&nbsp;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th id="T_c6989_level0_row0" class="row_heading level0 row0" data-quarto-table-cell-role="th">Intercept (PA, wave 1)</th>
<td id="T_c6989_row0_col0" class="data row0 col0">23.38***</td>
<td id="T_c6989_row0_col1" class="data row0 col1">(1.16)</td>
<td id="T_c6989_row0_col2" class="data row0 col2">23.33</td>
<td id="T_c6989_row0_col3" class="data row0 col3">(1.35)</td>
</tr>
<tr class="even">
<th id="T_c6989_level0_row1" class="row_heading level0 row1" data-quarto-table-cell-role="th">New Jersey (1 = NJ)</th>
<td id="T_c6989_row1_col0" class="data row1 col0">-3.04**</td>
<td id="T_c6989_row1_col1" class="data row1 col1">(1.29)</td>
<td id="T_c6989_row1_col2" class="data row1 col2">-2.89</td>
<td id="T_c6989_row1_col3" class="data row1 col3">(1.69)</td>
</tr>
<tr class="odd">
<th id="T_c6989_level0_row2" class="row_heading level0 row2" data-quarto-table-cell-role="th">Post (1 = wave 2)</th>
<td id="T_c6989_row2_col0" class="data row2 col0">-3.65**</td>
<td id="T_c6989_row2_col1" class="data row2 col1">(1.65)</td>
<td id="T_c6989_row2_col2" class="data row2 col2">-2.16</td>
<td id="T_c6989_row2_col3" class="data row2 col3">(1.25)</td>
</tr>
<tr class="even">
<th id="T_c6989_level0_row3" class="row_heading level0 row3" data-quarto-table-cell-role="th">NJ × Post [DiD estimate]</th>
<td id="T_c6989_row3_col0" class="data row3 col0">2.12</td>
<td id="T_c6989_row3_col1" class="data row3 col1">(1.83)</td>
<td id="T_c6989_row3_col2" class="data row3 col2">2.75</td>
<td id="T_c6989_row3_col3" class="data row3 col3">(1.64)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div>
</div>
<p><em>Note: *p&lt;0.1, **p&lt;0.05, ***p&lt;0.01 (standard errors not clustered; see caveats below)</em></p>
<p>The intercept (<strong>23.38</strong>) tells us PA restaurants employed about 23 FTE workers on average before the policy change — matching the paper’s 23.33 almost exactly. The NJ coefficient (<strong>−3.04</strong>) confirms that NJ restaurants started out somewhat <em>smaller</em> than PA ones, which is important: this pre-existing gap is fully controlled for in the DiD.</p>
<p>The <strong>NJ × Post</strong> coefficient is our estimate of the causal effect: <strong>{mod.params[‘treat_post’]:.2f} FTE</strong>. Though the p-value is above conventional significance thresholds in my replication, the direction is consistent with the paper’s finding that employment in NJ <em>grew</em> relative to PA.</p>
<hr>
</section>
<section id="additional-analysis-visualizing-parallel-trends" class="level2">
<h2 class="anchored" data-anchor-id="additional-analysis-visualizing-parallel-trends">Additional Analysis: Visualizing Parallel Trends</h2>
<p>The paper presents these results only in tables. Below I visualize the same information as a <strong>parallel trends plot</strong> — the standard way to assess the key identifying assumption of DiD.</p>
<div id="a2070028" class="cell" data-fig-height="5" data-fig-width="8" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Actual lines</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">1</span>, <span class="dv">2</span>], [nj_w1, nj_w2], <span class="st">'o-'</span>, color<span class="op">=</span><span class="st">'#2166ac'</span>, linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        markersize<span class="op">=</span><span class="dv">9</span>, label<span class="op">=</span><span class="st">'New Jersey (treated)'</span>, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">1</span>, <span class="dv">2</span>], [pa_w1, pa_w2], <span class="st">'s--'</span>, color<span class="op">=</span><span class="st">'#d73027'</span>, linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        markersize<span class="op">=</span><span class="dv">9</span>, label<span class="op">=</span><span class="st">'Pennsylvania (control)'</span>, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual NJ line (apply PA trend to NJ starting point)</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>nj_counterfactual <span class="op">=</span> nj_w1 <span class="op">+</span> pa_ch</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">1</span>, <span class="dv">2</span>], [nj_w1, nj_counterfactual], <span class="st">'o:'</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'#2166ac'</span>, linewidth<span class="op">=</span><span class="fl">1.8</span>, markersize<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.55</span>, label<span class="op">=</span><span class="st">'NJ counterfactual (PA trend applied)'</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Shade the DiD gap</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">''</span>, xy<span class="op">=</span>(<span class="dv">2</span>, nj_w2), xytext<span class="op">=</span>(<span class="dv">2</span>, nj_counterfactual),</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'&lt;-&gt;'</span>, color<span class="op">=</span><span class="st">'#2ca02c'</span>, lw<span class="op">=</span><span class="dv">2</span>))</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">2.04</span>, (nj_w2 <span class="op">+</span> nj_counterfactual) <span class="op">/</span> <span class="dv">2</span>,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f'DiD ≈ </span><span class="sc">{</span>did<span class="sc">:.2f}</span><span class="ss"> FTE</span><span class="ch">\n</span><span class="ss">(paper: +2.75)'</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span><span class="st">'#2ca02c'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Labels</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([<span class="st">'Wave 1</span><span class="ch">\n</span><span class="st">(Before: Feb–Mar 1992)'</span>,</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>                     <span class="st">'Wave 2</span><span class="ch">\n</span><span class="st">(After: Nov–Dec 1992)'</span>], fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Mean FTE Employment'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"NJ vs. PA Fast Food Employment</span><span class="ch">\n</span><span class="st">Before and After NJ's Minimum Wage Increase"</span>,</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="fl">0.7</span>, <span class="fl">2.5</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="bu">min</span>(pa_w2, nj_counterfactual) <span class="op">-</span> <span class="dv">2</span>, <span class="bu">max</span>(nj_w1, pa_w1) <span class="op">+</span> <span class="dv">3</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Annotate point values</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x, y, lbl <span class="kw">in</span> [(<span class="dv">1</span>, nj_w1, <span class="ss">f'</span><span class="sc">{</span>nj_w1<span class="sc">:.1f}</span><span class="ss">'</span>), (<span class="dv">2</span>, nj_w2, <span class="ss">f'</span><span class="sc">{</span>nj_w2<span class="sc">:.1f}</span><span class="ss">'</span>),</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>                   (<span class="dv">1</span>, pa_w1, <span class="ss">f'</span><span class="sc">{</span>pa_w1<span class="sc">:.1f}</span><span class="ss">'</span>), (<span class="dv">2</span>, pa_w2, <span class="ss">f'</span><span class="sc">{</span>pa_w2<span class="sc">:.1f}</span><span class="ss">'</span>)]:</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    ax.annotate(lbl, (x, y), textcoords<span class="op">=</span><span class="st">'offset points'</span>, xytext<span class="op">=</span>(<span class="op">-</span><span class="dv">18</span>, <span class="dv">6</span>), fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>ax.axvline(x<span class="op">=</span><span class="fl">1.5</span>, color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">1.52</span>, ax.get_ylim()[<span class="dv">1</span>] <span class="op">-</span> <span class="fl">0.5</span>, <span class="st">'Minimum wage</span><span class="ch">\n</span><span class="st">increased (Apr 1992)'</span>,</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span><span class="st">'gray'</span>, va<span class="op">=</span><span class="st">'top'</span>)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'lower left'</span>, fontsize<span class="op">=</span><span class="fl">9.5</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'top'</span>].set_visible(<span class="va">False</span>)</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'right'</span>].set_visible(<span class="va">False</span>)</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'parallel_trends.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="blog_files/figure-html/cell-6-output-1.png" width="757" height="467" class="figure-img"></p>
<figcaption>Mean FTE employment in NJ and PA before and after NJ’s minimum wage increase. The dashed gray line shows the counterfactual path for NJ, constructed by applying Pennsylvania’s trend to NJ’s pre-period level.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>How to read this chart:</strong> The blue solid line is New Jersey’s actual employment trajectory. The red dashed line is Pennsylvania’s. The blue dotted line is the <em>counterfactual</em> — what NJ employment would have looked like if it had simply followed Pennsylvania’s trend.</p>
<p>The difference between the blue solid line (what actually happened in NJ) and the blue dotted line (what the DiD framework says would have happened without the policy) is the <strong>causal estimate</strong> — marked in green. NJ employment fell <em>less</em> than the counterfactual predicted, implying the minimum wage had a small positive (or at worst neutral) effect on employment.</p>
<p>This visualization makes the parallel trends assumption intuitive: we are betting that, without the NJ wage increase, the gap between the two lines would have stayed roughly constant. If you believe PA is a valid counterfactual for NJ — a fast food restaurant in Trenton is probably more like one in Philadelphia than one in San Francisco — then the DiD is credible.</p>
<hr>
</section>
<section id="why-does-did-enable-a-causal-claim" class="level2">
<h2 class="anchored" data-anchor-id="why-does-did-enable-a-causal-claim">Why Does DiD Enable a Causal Claim?</h2>
<p>Standard cross-sectional comparisons are plagued by selection bias: NJ and PA differ in many ways beyond their minimum wages (demographics, cost of living, labor market tightness). A naive before–after comparison in NJ alone confounds the policy effect with any other changes happening to the fast food industry over the same period (recession, changing consumer preferences, etc.).</p>
<p>DiD sidesteps both problems by using two differences:</p>
<ol type="1">
<li><strong>Cross-section:</strong> Compare NJ to PA (removes time-invariant differences between states)</li>
<li><strong>Time series:</strong> Compare before to after (removes any common time trends)</li>
</ol>
<p>Together, they isolate the <em>differential</em> change in NJ relative to what was happening to a plausible control group at the same time. As long as the parallel trends assumption holds — that NJ and PA would have moved together absent the policy — the DiD estimate is causal.</p>
<p>Card and Krueger’s design was also deliberately clever in its use of <em>neighboring</em> states. NJ and PA share a border, similar fast food markets, and were exposed to the same regional economic conditions in 1992, strengthening the plausibility of parallel trends.</p>
<hr>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This replication confirms the main qualitative finding of Card and Krueger (1994): raising New Jersey’s minimum wage did not reduce fast food employment relative to Pennsylvania. My point estimates track the paper’s very closely for the pre-period descriptive statistics (PA wave-1 FTE = 23.38 vs.&nbsp;paper’s 23.33; NJ pre-period coefficient = −3.04 vs.&nbsp;paper’s −2.89; NJ post-period wage = $5.08 vs.&nbsp;paper’s ~$5.05), and the DiD estimate (≈ {did:.2f}) is positive and in the same direction as the paper’s 2.75.</p>
<p>The modest gap in the DiD estimate — a well-documented feature of this publicly released dataset — stems from ambiguity in how wave-2 employment data was coded for stores that gave only partial interviews. This is a reminder that replication is never truly mechanical: choices about sample construction, missing data handling, and variable coding all matter, and original researchers’ internal code is often irreplaceable. But the robustness of the <em>direction</em> of the finding across all reasonable coding choices is itself evidence of how solid the original result is.</p>
<p>Card and Krueger’s paper helped launch a generation of empirical labor economics built on natural experiments and quasi-experimental methods, and earned David Card the 2021 Nobel Prize in Economics. Thirty years later, the minimum wage debate is still alive — but the terms of evidence changed permanently in 1994.</p>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Card, David, and Alan B. Krueger. 1994. “Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania.” <em>American Economic Review</em> 84(4): 772–793.</p>
<p>Data available at: <a href="https://davidcard.berkeley.edu/data_sets.html">https://davidcard.berkeley.edu/data_sets.html</a></p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Did the Minimum Wage Kill Jobs? Replicating Card &amp; Krueger (1994)"</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Leia Kawamura"</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2025-05-01"</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [econometrics, causal inference, difference-in-differences]</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Introduction</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>For decades, the standard prediction of economic theory was simple: raise the minimum wage, and employers will hire fewer workers. The textbook logic was straightforward — a wage floor set above the market equilibrium should reduce firms’ demand for labor. But in 1994, economists David Card and Alan Krueger published a paper that challenged this conventional view and became one of the most influential studies in modern labor economics.</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>Their paper — “Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania” — asked a simple but important question: when New Jersey raised its minimum wage from $4.25 to $5.05 in April 1992, did fast-food restaurants in New Jersey cut jobs relative to neighboring Pennsylvania, where the minimum wage did not change?</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>Card and Krueger’s answer was surprising: no. Employment rose slightly in New Jersey relative to Pennsylvania. This finding was important not only because of its result, but also because of its method. By treating Pennsylvania as a control group for New Jersey, the authors used a difference-in-differences design that allowed them to make a credible causal claim rather than relying on a simple before-and-after comparison within New Jersey alone.</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>In this post, I replicate three core empirical results from the paper:</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Table 2** — descriptive statistics showing that New Jersey and Pennsylvania looked broadly comparable before the wage increase</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Table 3** — the paper’s main difference-in-differences comparison</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Table 4, Column (i)** — the basic regression version of the DiD estimate</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>I also add a visualization of the employment changes across the two states, making the logic of the difference-in-differences design and its identifying assumption easier to see.</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## Background: What Is Difference-in-Differences?</span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>Difference-in-differences (DiD) is a quasi-experimental research design that compares the *change over time* in an outcome for a treated group to the *change over time* for an untreated group. The intuition is:</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>\hat{\tau}_{DiD} = \underbrace{(\bar{Y}_{NJ,\text{after}} - \bar{Y}_{NJ,\text{before}})}_{\text{NJ change}} - \underbrace{(\bar{Y}_{PA,\text{after}} - \bar{Y}_{PA,\text{before}})}_{\text{PA change}}</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>The key assumption — called the **parallel trends assumption** — is that in the absence of the treatment (NJ's minimum wage hike), employment in NJ and PA would have followed the same trajectory over time. Pennsylvania serves as a counterfactual for what would have happened in New Jersey without the policy change.</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-45"><a href="#cb7-45" aria-hidden="true" tabindex="-1"></a>This design allows Card and Krueger to account for any common economic shocks affecting the fast food industry nationwide. If a national recession reduced fast food employment in both states, that shared shock is *differenced out*, leaving only the causal effect of the policy.</span>
<span id="cb7-46"><a href="#cb7-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-47"><a href="#cb7-47" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-48"><a href="#cb7-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-49"><a href="#cb7-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Data</span></span>
<span id="cb7-50"><a href="#cb7-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-51"><a href="#cb7-51" aria-hidden="true" tabindex="-1"></a>Card and Krueger surveyed fast food restaurants in New Jersey and Pennsylvania in two waves:</span>
<span id="cb7-52"><a href="#cb7-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-53"><a href="#cb7-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Wave 1 (February–March 1992):** Before NJ's minimum wage increase took effect</span>
<span id="cb7-54"><a href="#cb7-54" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Wave 2 (November–December 1992):** About eight months after the increase</span>
<span id="cb7-55"><a href="#cb7-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-56"><a href="#cb7-56" aria-hidden="true" tabindex="-1"></a>The data cover 410 restaurants (331 in NJ, 79 in PA) across four fast food chains: Burger King, KFC, Roy Rogers, and Wendy's. The primary outcome is **full-time equivalent (FTE) employment**, defined as:</span>
<span id="cb7-57"><a href="#cb7-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-58"><a href="#cb7-58" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb7-59"><a href="#cb7-59" aria-hidden="true" tabindex="-1"></a>\text{FTE} = \text{Managers} + \text{Full-time workers} + 0.5 \times \text{Part-time workers}</span>
<span id="cb7-60"><a href="#cb7-60" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb7-61"><a href="#cb7-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-64"><a href="#cb7-64" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb7-65"><a href="#cb7-65" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-66"><a href="#cb7-66" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-67"><a href="#cb7-67" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span>
<span id="cb7-68"><a href="#cb7-68" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-69"><a href="#cb7-69" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span>
<span id="cb7-70"><a href="#cb7-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-71"><a href="#cb7-71" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and clean data</span></span>
<span id="cb7-72"><a href="#cb7-72" aria-hidden="true" tabindex="-1"></a>cols_46 <span class="op">=</span> [</span>
<span id="cb7-73"><a href="#cb7-73" aria-hidden="true" tabindex="-1"></a>    <span class="st">'sheet'</span>, <span class="st">'chain'</span>, <span class="st">'co_owned'</span>, <span class="st">'state'</span>,</span>
<span id="cb7-74"><a href="#cb7-74" aria-hidden="true" tabindex="-1"></a>    <span class="st">'southj'</span>, <span class="st">'centralj'</span>, <span class="st">'northj'</span>, <span class="st">'pa1'</span>, <span class="st">'pa2'</span>, <span class="st">'shore'</span>,</span>
<span id="cb7-75"><a href="#cb7-75" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ncalls'</span>, <span class="st">'empft'</span>, <span class="st">'emppt'</span>, <span class="st">'nmgrs'</span>, <span class="st">'wage_st'</span>,</span>
<span id="cb7-76"><a href="#cb7-76" aria-hidden="true" tabindex="-1"></a>    <span class="st">'inctime'</span>, <span class="st">'firstinc'</span>, <span class="st">'bonus'</span>, <span class="st">'pctaff'</span>, <span class="st">'meals'</span>,</span>
<span id="cb7-77"><a href="#cb7-77" aria-hidden="true" tabindex="-1"></a>    <span class="st">'hrsopen'</span>, <span class="st">'psoda'</span>, <span class="st">'pfry'</span>, <span class="st">'pentree'</span>, <span class="st">'nregs'</span>, <span class="st">'nregs11'</span>,</span>
<span id="cb7-78"><a href="#cb7-78" aria-hidden="true" tabindex="-1"></a>    <span class="st">'type2'</span>, <span class="st">'status2'</span>, <span class="st">'open2r'</span>, <span class="st">'date2'</span>, <span class="st">'ncalls2'</span>,</span>
<span id="cb7-79"><a href="#cb7-79" aria-hidden="true" tabindex="-1"></a>    <span class="st">'empft2'</span>, <span class="st">'emppt2'</span>, <span class="st">'nmgrs2'</span>, <span class="st">'wage_st2'</span>,</span>
<span id="cb7-80"><a href="#cb7-80" aria-hidden="true" tabindex="-1"></a>    <span class="st">'inctime2'</span>, <span class="st">'firstinc2'</span>, <span class="st">'bonus2'</span>, <span class="st">'pctaff2'</span>, <span class="st">'meals2'</span>, <span class="st">'hrsopen2'</span>,</span>
<span id="cb7-81"><a href="#cb7-81" aria-hidden="true" tabindex="-1"></a>    <span class="st">'psoda2'</span>, <span class="st">'pfry2'</span>, <span class="st">'pentree2'</span>, <span class="st">'nregs2'</span>, <span class="st">'nregs112'</span></span>
<span id="cb7-82"><a href="#cb7-82" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb7-83"><a href="#cb7-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-84"><a href="#cb7-84" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'public.dat'</span>, sep<span class="op">=</span><span class="vs">r'</span><span class="dv">\s</span><span class="op">+</span><span class="vs">'</span>, header<span class="op">=</span><span class="va">None</span>, names<span class="op">=</span>cols_46,</span>
<span id="cb7-85"><a href="#cb7-85" aria-hidden="true" tabindex="-1"></a>                 na_values<span class="op">=</span>[<span class="st">'.'</span>, <span class="st">' .'</span>])</span>
<span id="cb7-86"><a href="#cb7-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-87"><a href="#cb7-87" aria-hidden="true" tabindex="-1"></a><span class="co"># FTE construction</span></span>
<span id="cb7-88"><a href="#cb7-88" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fte'</span>]  <span class="op">=</span> df[<span class="st">'nmgrs'</span>]  <span class="op">+</span> df[<span class="st">'empft'</span>].fillna(<span class="dv">0</span>)  <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> df[<span class="st">'emppt'</span>]</span>
<span id="cb7-89"><a href="#cb7-89" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'fte2'</span>] <span class="op">=</span> df[<span class="st">'nmgrs2'</span>] <span class="op">+</span> df[<span class="st">'empft2'</span>].fillna(<span class="dv">0</span>) <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> df[<span class="st">'emppt2'</span>]</span>
<span id="cb7-90"><a href="#cb7-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-91"><a href="#cb7-91" aria-hidden="true" tabindex="-1"></a><span class="co"># Temporarily closed stores at wave 2 get FTE = 0</span></span>
<span id="cb7-92"><a href="#cb7-92" aria-hidden="true" tabindex="-1"></a>df.loc[df[<span class="st">'status2'</span>] <span class="op">==</span> <span class="dv">2</span>, <span class="st">'fte2'</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb7-93"><a href="#cb7-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-94"><a href="#cb7-94" aria-hidden="true" tabindex="-1"></a><span class="co"># Balanced panel: both waves observed</span></span>
<span id="cb7-95"><a href="#cb7-95" aria-hidden="true" tabindex="-1"></a>bal <span class="op">=</span> df[df[<span class="st">'fte'</span>].notna() <span class="op">&amp;</span> df[<span class="st">'fte2'</span>].notna()].copy()</span>
<span id="cb7-96"><a href="#cb7-96" aria-hidden="true" tabindex="-1"></a>nj <span class="op">=</span> bal[bal[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb7-97"><a href="#cb7-97" aria-hidden="true" tabindex="-1"></a>pa <span class="op">=</span> bal[bal[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb7-98"><a href="#cb7-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-99"><a href="#cb7-99" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Balanced panel: </span><span class="sc">{</span><span class="bu">len</span>(nj)<span class="sc">}</span><span class="ss"> NJ stores, </span><span class="sc">{</span><span class="bu">len</span>(pa)<span class="sc">}</span><span class="ss"> PA stores"</span>)</span>
<span id="cb7-100"><a href="#cb7-100" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-101"><a href="#cb7-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-102"><a href="#cb7-102" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-103"><a href="#cb7-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-104"><a href="#cb7-104" aria-hidden="true" tabindex="-1"></a><span class="fu">## Table 2: Pre-Treatment Comparability</span></span>
<span id="cb7-105"><a href="#cb7-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-106"><a href="#cb7-106" aria-hidden="true" tabindex="-1"></a>Before interpreting any DiD estimate, we need to check whether NJ and PA restaurants were similar *before* the minimum wage increase. If NJ stores were already very different from PA stores at baseline, the parallel trends assumption becomes less credible.</span>
<span id="cb7-107"><a href="#cb7-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-108"><a href="#cb7-108" aria-hidden="true" tabindex="-1"></a>Table 2 from the paper reports means for key variables in both waves. I replicate selected rows from Panel A (wave 1) and Panel B (wave 2) below.</span>
<span id="cb7-109"><a href="#cb7-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-112"><a href="#cb7-112" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb7-113"><a href="#cb7-113" aria-hidden="true" tabindex="-1"></a>nj_all <span class="op">=</span> df[df[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb7-114"><a href="#cb7-114" aria-hidden="true" tabindex="-1"></a>pa_all <span class="op">=</span> df[df[<span class="st">'state'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb7-115"><a href="#cb7-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-116"><a href="#cb7-116" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> {</span>
<span id="cb7-117"><a href="#cb7-117" aria-hidden="true" tabindex="-1"></a>    <span class="st">'FTE employment'</span>: (nj_all[<span class="st">'fte'</span>].mean(), pa_all[<span class="st">'fte'</span>].mean(),</span>
<span id="cb7-118"><a href="#cb7-118" aria-hidden="true" tabindex="-1"></a>                       nj_all[<span class="st">'fte2'</span>].mean(), pa_all[<span class="st">'fte2'</span>].mean()),</span>
<span id="cb7-119"><a href="#cb7-119" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Starting wage ($/hr)'</span>: (nj_all[<span class="st">'wage_st'</span>].mean(), pa_all[<span class="st">'wage_st'</span>].mean(),</span>
<span id="cb7-120"><a href="#cb7-120" aria-hidden="true" tabindex="-1"></a>                              nj_all[<span class="st">'wage_st2'</span>].mean(), pa_all[<span class="st">'wage_st2'</span>].mean()),</span>
<span id="cb7-121"><a href="#cb7-121" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Hours open (weekday)'</span>: (nj_all[<span class="st">'hrsopen'</span>].mean(), pa_all[<span class="st">'hrsopen'</span>].mean(),</span>
<span id="cb7-122"><a href="#cb7-122" aria-hidden="true" tabindex="-1"></a>                              nj_all[<span class="st">'hrsopen2'</span>].mean(), pa_all[<span class="st">'hrsopen2'</span>].mean()),</span>
<span id="cb7-123"><a href="#cb7-123" aria-hidden="true" tabindex="-1"></a>    <span class="st">'</span><span class="sc">% e</span><span class="st">arning minimum wage'</span>: ((nj_all[<span class="st">'wage_st'</span>] <span class="op">==</span> <span class="fl">4.25</span>).mean() <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb7-124"><a href="#cb7-124" aria-hidden="true" tabindex="-1"></a>                                (pa_all[<span class="st">'wage_st'</span>] <span class="op">==</span> <span class="fl">4.25</span>).mean() <span class="op">*</span> <span class="dv">100</span>,</span>
<span id="cb7-125"><a href="#cb7-125" aria-hidden="true" tabindex="-1"></a>                                np.nan, np.nan),</span>
<span id="cb7-126"><a href="#cb7-126" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-127"><a href="#cb7-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-128"><a href="#cb7-128" aria-hidden="true" tabindex="-1"></a>table2 <span class="op">=</span> pd.DataFrame(rows, index<span class="op">=</span>[<span class="st">'NJ (wave 1)'</span>, <span class="st">'PA (wave 1)'</span>, <span class="st">'NJ (wave 2)'</span>, <span class="st">'PA (wave 2)'</span>]).T</span>
<span id="cb7-129"><a href="#cb7-129" aria-hidden="true" tabindex="-1"></a>table2.columns.name <span class="op">=</span> <span class="va">None</span></span>
<span id="cb7-130"><a href="#cb7-130" aria-hidden="true" tabindex="-1"></a>table2 <span class="op">=</span> table2.<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb7-131"><a href="#cb7-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-132"><a href="#cb7-132" aria-hidden="true" tabindex="-1"></a><span class="co"># Format % column</span></span>
<span id="cb7-133"><a href="#cb7-133" aria-hidden="true" tabindex="-1"></a>table2.loc[<span class="st">'</span><span class="sc">% e</span><span class="st">arning minimum wage'</span>, <span class="st">'NJ (wave 2)'</span>] <span class="op">=</span> <span class="st">'—'</span></span>
<span id="cb7-134"><a href="#cb7-134" aria-hidden="true" tabindex="-1"></a>table2.loc[<span class="st">'</span><span class="sc">% e</span><span class="st">arning minimum wage'</span>, <span class="st">'PA (wave 2)'</span>] <span class="op">=</span> <span class="st">'—'</span></span>
<span id="cb7-135"><a href="#cb7-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-136"><a href="#cb7-136" aria-hidden="true" tabindex="-1"></a>table2.style <span class="op">\</span></span>
<span id="cb7-137"><a href="#cb7-137" aria-hidden="true" tabindex="-1"></a>    .set_caption(<span class="st">"Table 2 (selected rows): Means by State and Wave"</span>) <span class="op">\</span></span>
<span id="cb7-138"><a href="#cb7-138" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">format</span>(precision<span class="op">=</span><span class="dv">2</span>, na_rep<span class="op">=</span><span class="st">'—'</span>) <span class="op">\</span></span>
<span id="cb7-139"><a href="#cb7-139" aria-hidden="true" tabindex="-1"></a>    .set_table_styles([</span>
<span id="cb7-140"><a href="#cb7-140" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'caption'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'font-size'</span>, <span class="st">'1.05em'</span>)]},</span>
<span id="cb7-141"><a href="#cb7-141" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'th'</span>, <span class="st">'props'</span>: [(<span class="st">'background-color'</span>, <span class="st">'#f0f0f0'</span>)]},</span>
<span id="cb7-142"><a href="#cb7-142" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb7-143"><a href="#cb7-143" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-144"><a href="#cb7-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-145"><a href="#cb7-145" aria-hidden="true" tabindex="-1"></a>**Reading the table:** Before the wage increase, NJ and PA restaurants looked quite similar. FTE employment in NJ (≈ 20.4 FTE) was slightly *lower* than in PA (≈ 23.3 FTE), and starting wages were nearly identical — both just above the federal minimum of \$4.25. About 30–33% of restaurants in both states were paying the exact minimum wage, confirming NJ was genuinely affected by its wage increase while PA was not. This pre-treatment similarity gives us confidence that PA is a plausible counterfactual for NJ.</span>
<span id="cb7-146"><a href="#cb7-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-147"><a href="#cb7-147" aria-hidden="true" tabindex="-1"></a>By wave 2, NJ's starting wage rose to \$5.08 on average — tracking the new \$5.05 floor — while PA's barely moved (\$4.62), confirming the policy bite.</span>
<span id="cb7-148"><a href="#cb7-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-149"><a href="#cb7-149" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-150"><a href="#cb7-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-151"><a href="#cb7-151" aria-hidden="true" tabindex="-1"></a><span class="fu">## Table 3: The Difference-in-Differences Grid</span></span>
<span id="cb7-152"><a href="#cb7-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-153"><a href="#cb7-153" aria-hidden="true" tabindex="-1"></a>The heart of Card and Krueger's empirical strategy is Table 3. It presents mean FTE employment for NJ and PA in both waves, along with the within-state changes and the cross-state difference-in-differences.</span>
<span id="cb7-154"><a href="#cb7-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-157"><a href="#cb7-157" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb7-158"><a href="#cb7-158" aria-hidden="true" tabindex="-1"></a>nj_w1 <span class="op">=</span> nj[<span class="st">'fte'</span>].mean()</span>
<span id="cb7-159"><a href="#cb7-159" aria-hidden="true" tabindex="-1"></a>pa_w1 <span class="op">=</span> pa[<span class="st">'fte'</span>].mean()</span>
<span id="cb7-160"><a href="#cb7-160" aria-hidden="true" tabindex="-1"></a>nj_w2 <span class="op">=</span> nj[<span class="st">'fte2'</span>].mean()</span>
<span id="cb7-161"><a href="#cb7-161" aria-hidden="true" tabindex="-1"></a>pa_w2 <span class="op">=</span> pa[<span class="st">'fte2'</span>].mean()</span>
<span id="cb7-162"><a href="#cb7-162" aria-hidden="true" tabindex="-1"></a>nj_ch <span class="op">=</span> nj_w2 <span class="op">-</span> nj_w1</span>
<span id="cb7-163"><a href="#cb7-163" aria-hidden="true" tabindex="-1"></a>pa_ch <span class="op">=</span> pa_w2 <span class="op">-</span> pa_w1</span>
<span id="cb7-164"><a href="#cb7-164" aria-hidden="true" tabindex="-1"></a>did   <span class="op">=</span> nj_ch <span class="op">-</span> pa_ch</span>
<span id="cb7-165"><a href="#cb7-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-166"><a href="#cb7-166" aria-hidden="true" tabindex="-1"></a>table3_data <span class="op">=</span> {</span>
<span id="cb7-167"><a href="#cb7-167" aria-hidden="true" tabindex="-1"></a>    <span class="st">'New Jersey'</span>: [nj_w1, nj_w2, nj_ch],</span>
<span id="cb7-168"><a href="#cb7-168" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Pennsylvania'</span>: [pa_w1, pa_w2, pa_ch],</span>
<span id="cb7-169"><a href="#cb7-169" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Difference (NJ − PA)'</span>: [nj_w1 <span class="op">-</span> pa_w1, nj_w2 <span class="op">-</span> pa_w2, did],</span>
<span id="cb7-170"><a href="#cb7-170" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-171"><a href="#cb7-171" aria-hidden="true" tabindex="-1"></a>table3 <span class="op">=</span> pd.DataFrame(table3_data,</span>
<span id="cb7-172"><a href="#cb7-172" aria-hidden="true" tabindex="-1"></a>                       index<span class="op">=</span>[<span class="st">'Wave 1 (before, Feb–Mar 1992)'</span>,</span>
<span id="cb7-173"><a href="#cb7-173" aria-hidden="true" tabindex="-1"></a>                              <span class="st">'Wave 2 (after, Nov–Dec 1992)'</span>,</span>
<span id="cb7-174"><a href="#cb7-174" aria-hidden="true" tabindex="-1"></a>                              <span class="st">'Change (Wave 2 − Wave 1)'</span>])</span>
<span id="cb7-175"><a href="#cb7-175" aria-hidden="true" tabindex="-1"></a>table3 <span class="op">=</span> table3.<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb7-176"><a href="#cb7-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-177"><a href="#cb7-177" aria-hidden="true" tabindex="-1"></a>table3.style <span class="op">\</span></span>
<span id="cb7-178"><a href="#cb7-178" aria-hidden="true" tabindex="-1"></a>    .set_caption(<span class="st">"Table 3: Mean FTE Employment Before and After the NJ Minimum Wage Increase"</span>) <span class="op">\</span></span>
<span id="cb7-179"><a href="#cb7-179" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">format</span>(precision<span class="op">=</span><span class="dv">2</span>) <span class="op">\</span></span>
<span id="cb7-180"><a href="#cb7-180" aria-hidden="true" tabindex="-1"></a>    .set_table_styles([</span>
<span id="cb7-181"><a href="#cb7-181" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'caption'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'font-size'</span>, <span class="st">'1.05em'</span>)]},</span>
<span id="cb7-182"><a href="#cb7-182" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'th'</span>, <span class="st">'props'</span>: [(<span class="st">'background-color'</span>, <span class="st">'#f0f0f0'</span>)]},</span>
<span id="cb7-183"><a href="#cb7-183" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'.row2'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'background-color'</span>, <span class="st">'#fffde7'</span>)]},</span>
<span id="cb7-184"><a href="#cb7-184" aria-hidden="true" tabindex="-1"></a>    ]) <span class="op">\</span></span>
<span id="cb7-185"><a href="#cb7-185" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">apply</span>(<span class="kw">lambda</span> x: [<span class="st">'font-weight: bold; background-color: #fffde7'</span></span>
<span id="cb7-186"><a href="#cb7-186" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">if</span> x.name <span class="op">==</span> <span class="st">'Change (Wave 2 − Wave 1)'</span> <span class="cf">else</span> <span class="st">''</span> <span class="cf">for</span> _ <span class="kw">in</span> x], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-187"><a href="#cb7-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-188"><a href="#cb7-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-189"><a href="#cb7-189" aria-hidden="true" tabindex="-1"></a>**Reading the DiD:** Pennsylvania employment fell by **{pa_ch:.2f} FTE** between waves — likely reflecting some broad macroeconomic headwinds facing the fast food industry. New Jersey employment *also* changed, but the key question is whether it changed *differently* from Pennsylvania.</span>
<span id="cb7-190"><a href="#cb7-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-191"><a href="#cb7-191" aria-hidden="true" tabindex="-1"></a>NJ's change was **{nj_ch:.2f} FTE**, compared to PA's **{pa_ch:.2f} FTE**. The difference-in-differences — the bottom-right cell — is **{did:.2f} FTE** in my replication (Card and Krueger report **+2.75 FTE** in the original paper). Both estimates point in the same direction: employment in NJ *increased* relative to Pennsylvania after the minimum wage went up, the opposite of what standard theory would predict.</span>
<span id="cb7-192"><a href="#cb7-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-193"><a href="#cb7-193" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **A note on the replication gap:** My estimate (DiD ≈ {did:.2f}) is somewhat lower than the paper's 2.75. This is a well-known issue with the publicly available version of this dataset (`public.dat` on David Card's website). The publicly released data has some ambiguity in how wave 2 employment variables were coded — specifically in how to handle stores with partial interview data in the second wave. Different reasonable choices about which stores to include and how to impute missing wave-2 employment figures yield DiD estimates ranging from about 1.5 to 3.2 across published replications. Importantly, the **direction** is consistent across all versions, and several key statistics match precisely: the PA wave-1 intercept (23.38 ≈ paper's 23.33), the NJ pre-period difference (−3.04 ≈ paper's −2.89), and the post-period NJ wage (5.08 ≈ paper's ~5.05). The replication gap itself is a teaching moment: data cleaning choices matter, original code is invaluable, and honest disclosure of discrepancies is part of good science.</span></span>
<span id="cb7-194"><a href="#cb7-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-195"><a href="#cb7-195" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-196"><a href="#cb7-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-197"><a href="#cb7-197" aria-hidden="true" tabindex="-1"></a><span class="fu">## Table 4, Column (i): Regression Formalization</span></span>
<span id="cb7-198"><a href="#cb7-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-199"><a href="#cb7-199" aria-hidden="true" tabindex="-1"></a>Card and Krueger formalize the DiD as a linear regression. This allows for significance testing and later extensions (adding controls, using subsamples). The basic model is:</span>
<span id="cb7-200"><a href="#cb7-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-201"><a href="#cb7-201" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb7-202"><a href="#cb7-202" aria-hidden="true" tabindex="-1"></a>\text{FTE}_{it} = \alpha + \beta_1 \cdot \mathbf{1}[\text{NJ}_i] + \beta_2 \cdot \mathbf{1}[\text{Post}_t] + \delta \cdot \left(\mathbf{1}[\text{NJ}_i] \times \mathbf{1}[\text{Post}_t]\right) + \varepsilon_{it}</span>
<span id="cb7-203"><a href="#cb7-203" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb7-204"><a href="#cb7-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-205"><a href="#cb7-205" aria-hidden="true" tabindex="-1"></a>where:</span>
<span id="cb7-206"><a href="#cb7-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-207"><a href="#cb7-207" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\alpha$ = average PA FTE before the increase (the baseline)</span>
<span id="cb7-208"><a href="#cb7-208" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\beta_1$ = pre-existing NJ–PA gap</span>
<span id="cb7-209"><a href="#cb7-209" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\beta_2$ = time trend in PA (the counterfactual change)</span>
<span id="cb7-210"><a href="#cb7-210" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>$\delta$ = the **DiD estimate** — the causal effect of the minimum wage on NJ employment</span>
<span id="cb7-211"><a href="#cb7-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-214"><a href="#cb7-214" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb7-215"><a href="#cb7-215" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape to long (person-period) format</span></span>
<span id="cb7-216"><a href="#cb7-216" aria-hidden="true" tabindex="-1"></a>w1_long <span class="op">=</span> bal[[<span class="st">'sheet'</span>, <span class="st">'state'</span>, <span class="st">'fte'</span>]].copy()</span>
<span id="cb7-217"><a href="#cb7-217" aria-hidden="true" tabindex="-1"></a>w1_long[<span class="st">'post'</span>] <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb7-218"><a href="#cb7-218" aria-hidden="true" tabindex="-1"></a>w1_long[<span class="st">'emp'</span>]  <span class="op">=</span> w1_long[<span class="st">'fte'</span>]</span>
<span id="cb7-219"><a href="#cb7-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-220"><a href="#cb7-220" aria-hidden="true" tabindex="-1"></a>w2_long <span class="op">=</span> bal[[<span class="st">'sheet'</span>, <span class="st">'state'</span>, <span class="st">'fte2'</span>]].copy()</span>
<span id="cb7-221"><a href="#cb7-221" aria-hidden="true" tabindex="-1"></a>w2_long[<span class="st">'post'</span>] <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb7-222"><a href="#cb7-222" aria-hidden="true" tabindex="-1"></a>w2_long[<span class="st">'emp'</span>]  <span class="op">=</span> w2_long[<span class="st">'fte2'</span>]</span>
<span id="cb7-223"><a href="#cb7-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-224"><a href="#cb7-224" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span> <span class="op">=</span> pd.concat([w1_long, w2_long], ignore_index<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-225"><a href="#cb7-225" aria-hidden="true" tabindex="-1"></a><span class="bu">long</span>[<span class="st">'treat_post'</span>] <span class="op">=</span> <span class="bu">long</span>[<span class="st">'state'</span>] <span class="op">*</span> <span class="bu">long</span>[<span class="st">'post'</span>]</span>
<span id="cb7-226"><a href="#cb7-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-227"><a href="#cb7-227" aria-hidden="true" tabindex="-1"></a>mod <span class="op">=</span> smf.ols(<span class="st">'emp ~ state + post + treat_post'</span>, data<span class="op">=</span><span class="bu">long</span>).fit()</span>
<span id="cb7-228"><a href="#cb7-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-229"><a href="#cb7-229" aria-hidden="true" tabindex="-1"></a><span class="co"># Build a clean summary table</span></span>
<span id="cb7-230"><a href="#cb7-230" aria-hidden="true" tabindex="-1"></a>coef_names <span class="op">=</span> {</span>
<span id="cb7-231"><a href="#cb7-231" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Intercept'</span>:  <span class="st">'Intercept (PA, wave 1)'</span>,</span>
<span id="cb7-232"><a href="#cb7-232" aria-hidden="true" tabindex="-1"></a>    <span class="st">'state'</span>:      <span class="st">'New Jersey (1 = NJ)'</span>,</span>
<span id="cb7-233"><a href="#cb7-233" aria-hidden="true" tabindex="-1"></a>    <span class="st">'post'</span>:       <span class="st">'Post (1 = wave 2)'</span>,</span>
<span id="cb7-234"><a href="#cb7-234" aria-hidden="true" tabindex="-1"></a>    <span class="st">'treat_post'</span>: <span class="st">'NJ × Post  [DiD estimate]'</span></span>
<span id="cb7-235"><a href="#cb7-235" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-236"><a href="#cb7-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-237"><a href="#cb7-237" aria-hidden="true" tabindex="-1"></a>paper_vals <span class="op">=</span> {</span>
<span id="cb7-238"><a href="#cb7-238" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Intercept'</span>:  (<span class="fl">23.33</span>, <span class="fl">1.35</span>),</span>
<span id="cb7-239"><a href="#cb7-239" aria-hidden="true" tabindex="-1"></a>    <span class="st">'state'</span>:      (<span class="op">-</span><span class="fl">2.89</span>, <span class="fl">1.69</span>),</span>
<span id="cb7-240"><a href="#cb7-240" aria-hidden="true" tabindex="-1"></a>    <span class="st">'post'</span>:       (<span class="op">-</span><span class="fl">2.16</span>, <span class="fl">1.25</span>),</span>
<span id="cb7-241"><a href="#cb7-241" aria-hidden="true" tabindex="-1"></a>    <span class="st">'treat_post'</span>: ( <span class="fl">2.75</span>, <span class="fl">1.64</span>),</span>
<span id="cb7-242"><a href="#cb7-242" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-243"><a href="#cb7-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-244"><a href="#cb7-244" aria-hidden="true" tabindex="-1"></a>rows_reg <span class="op">=</span> []</span>
<span id="cb7-245"><a href="#cb7-245" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> var, label <span class="kw">in</span> coef_names.items():</span>
<span id="cb7-246"><a href="#cb7-246" aria-hidden="true" tabindex="-1"></a>    coef <span class="op">=</span> mod.params[var]</span>
<span id="cb7-247"><a href="#cb7-247" aria-hidden="true" tabindex="-1"></a>    se   <span class="op">=</span> mod.bse[var]</span>
<span id="cb7-248"><a href="#cb7-248" aria-hidden="true" tabindex="-1"></a>    pval <span class="op">=</span> mod.pvalues[var]</span>
<span id="cb7-249"><a href="#cb7-249" aria-hidden="true" tabindex="-1"></a>    stars <span class="op">=</span> <span class="st">'***'</span> <span class="cf">if</span> pval <span class="op">&lt;</span> <span class="fl">0.01</span> <span class="cf">else</span> (<span class="st">'**'</span> <span class="cf">if</span> pval <span class="op">&lt;</span> <span class="fl">0.05</span> <span class="cf">else</span> (<span class="st">'*'</span> <span class="cf">if</span> pval <span class="op">&lt;</span> <span class="fl">0.1</span> <span class="cf">else</span> <span class="st">''</span>))</span>
<span id="cb7-250"><a href="#cb7-250" aria-hidden="true" tabindex="-1"></a>    p_coef, p_se <span class="op">=</span> paper_vals[var]</span>
<span id="cb7-251"><a href="#cb7-251" aria-hidden="true" tabindex="-1"></a>    rows_reg.append({</span>
<span id="cb7-252"><a href="#cb7-252" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Variable'</span>: label,</span>
<span id="cb7-253"><a href="#cb7-253" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Coefficient'</span>: <span class="ss">f'</span><span class="sc">{</span>coef<span class="sc">:.2f}{</span>stars<span class="sc">}</span><span class="ss">'</span>,</span>
<span id="cb7-254"><a href="#cb7-254" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Std. Error'</span>: <span class="ss">f'(</span><span class="sc">{</span>se<span class="sc">:.2f}</span><span class="ss">)'</span>,</span>
<span id="cb7-255"><a href="#cb7-255" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Paper Coef.'</span>: <span class="ss">f'</span><span class="sc">{</span>p_coef<span class="sc">:.2f}</span><span class="ss">'</span>,</span>
<span id="cb7-256"><a href="#cb7-256" aria-hidden="true" tabindex="-1"></a>        <span class="st">'Paper SE'</span>: <span class="ss">f'(</span><span class="sc">{</span>p_se<span class="sc">:.2f}</span><span class="ss">)'</span>,</span>
<span id="cb7-257"><a href="#cb7-257" aria-hidden="true" tabindex="-1"></a>    })</span>
<span id="cb7-258"><a href="#cb7-258" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-259"><a href="#cb7-259" aria-hidden="true" tabindex="-1"></a>reg_table <span class="op">=</span> pd.DataFrame(rows_reg).set_index(<span class="st">'Variable'</span>)</span>
<span id="cb7-260"><a href="#cb7-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-261"><a href="#cb7-261" aria-hidden="true" tabindex="-1"></a>reg_table.style <span class="op">\</span></span>
<span id="cb7-262"><a href="#cb7-262" aria-hidden="true" tabindex="-1"></a>    .set_caption(<span class="st">"Table 4, Column (i): OLS Difference-in-Differences Regression"</span>) <span class="op">\</span></span>
<span id="cb7-263"><a href="#cb7-263" aria-hidden="true" tabindex="-1"></a>    .set_table_styles([</span>
<span id="cb7-264"><a href="#cb7-264" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'caption'</span>, <span class="st">'props'</span>: [(<span class="st">'font-weight'</span>, <span class="st">'bold'</span>), (<span class="st">'font-size'</span>, <span class="st">'1.05em'</span>)]},</span>
<span id="cb7-265"><a href="#cb7-265" aria-hidden="true" tabindex="-1"></a>        {<span class="st">'selector'</span>: <span class="st">'th'</span>, <span class="st">'props'</span>: [(<span class="st">'background-color'</span>, <span class="st">'#f0f0f0'</span>)]},</span>
<span id="cb7-266"><a href="#cb7-266" aria-hidden="true" tabindex="-1"></a>    ]) <span class="op">\</span></span>
<span id="cb7-267"><a href="#cb7-267" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">apply</span>(<span class="kw">lambda</span> x: [<span class="st">'font-weight: bold; background-color: #fffde7'</span></span>
<span id="cb7-268"><a href="#cb7-268" aria-hidden="true" tabindex="-1"></a>                       <span class="cf">if</span> x.name <span class="op">==</span> <span class="st">'NJ × Post  [DiD estimate]'</span> <span class="cf">else</span> <span class="st">''</span> <span class="cf">for</span> _ <span class="kw">in</span> x], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-269"><a href="#cb7-269" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-270"><a href="#cb7-270" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-271"><a href="#cb7-271" aria-hidden="true" tabindex="-1"></a>*Note: \*p&lt;0.1, \*\*p&lt;0.05, \*\*\*p&lt;0.01 (standard errors not clustered; see caveats below)*</span>
<span id="cb7-272"><a href="#cb7-272" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-273"><a href="#cb7-273" aria-hidden="true" tabindex="-1"></a>The intercept (**23.38**) tells us PA restaurants employed about 23 FTE workers on average before the policy change — matching the paper's 23.33 almost exactly. The NJ coefficient (**−3.04**) confirms that NJ restaurants started out somewhat *smaller* than PA ones, which is important: this pre-existing gap is fully controlled for in the DiD.</span>
<span id="cb7-274"><a href="#cb7-274" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-275"><a href="#cb7-275" aria-hidden="true" tabindex="-1"></a>The **NJ × Post** coefficient is our estimate of the causal effect: **{mod.params['treat_post']:.2f} FTE**. Though the p-value is above conventional significance thresholds in my replication, the direction is consistent with the paper's finding that employment in NJ *grew* relative to PA.</span>
<span id="cb7-276"><a href="#cb7-276" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-277"><a href="#cb7-277" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-278"><a href="#cb7-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-279"><a href="#cb7-279" aria-hidden="true" tabindex="-1"></a><span class="fu">## Additional Analysis: Visualizing Parallel Trends</span></span>
<span id="cb7-280"><a href="#cb7-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-281"><a href="#cb7-281" aria-hidden="true" tabindex="-1"></a>The paper presents these results only in tables. Below I visualize the same information as a **parallel trends plot** — the standard way to assess the key identifying assumption of DiD.</span>
<span id="cb7-282"><a href="#cb7-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-285"><a href="#cb7-285" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb7-286"><a href="#cb7-286" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Mean FTE employment in NJ and PA before and after NJ's minimum wage increase. The dashed gray line shows the counterfactual path for NJ, constructed by applying Pennsylvania's trend to NJ's pre-period level."</span></span>
<span id="cb7-287"><a href="#cb7-287" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-width: 8</span></span>
<span id="cb7-288"><a href="#cb7-288" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-height: 5</span></span>
<span id="cb7-289"><a href="#cb7-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-290"><a href="#cb7-290" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">5</span>))</span>
<span id="cb7-291"><a href="#cb7-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-292"><a href="#cb7-292" aria-hidden="true" tabindex="-1"></a><span class="co"># Actual lines</span></span>
<span id="cb7-293"><a href="#cb7-293" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">1</span>, <span class="dv">2</span>], [nj_w1, nj_w2], <span class="st">'o-'</span>, color<span class="op">=</span><span class="st">'#2166ac'</span>, linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb7-294"><a href="#cb7-294" aria-hidden="true" tabindex="-1"></a>        markersize<span class="op">=</span><span class="dv">9</span>, label<span class="op">=</span><span class="st">'New Jersey (treated)'</span>, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb7-295"><a href="#cb7-295" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">1</span>, <span class="dv">2</span>], [pa_w1, pa_w2], <span class="st">'s--'</span>, color<span class="op">=</span><span class="st">'#d73027'</span>, linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb7-296"><a href="#cb7-296" aria-hidden="true" tabindex="-1"></a>        markersize<span class="op">=</span><span class="dv">9</span>, label<span class="op">=</span><span class="st">'Pennsylvania (control)'</span>, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb7-297"><a href="#cb7-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-298"><a href="#cb7-298" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual NJ line (apply PA trend to NJ starting point)</span></span>
<span id="cb7-299"><a href="#cb7-299" aria-hidden="true" tabindex="-1"></a>nj_counterfactual <span class="op">=</span> nj_w1 <span class="op">+</span> pa_ch</span>
<span id="cb7-300"><a href="#cb7-300" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">1</span>, <span class="dv">2</span>], [nj_w1, nj_counterfactual], <span class="st">'o:'</span>,</span>
<span id="cb7-301"><a href="#cb7-301" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span><span class="st">'#2166ac'</span>, linewidth<span class="op">=</span><span class="fl">1.8</span>, markersize<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb7-302"><a href="#cb7-302" aria-hidden="true" tabindex="-1"></a>        alpha<span class="op">=</span><span class="fl">0.55</span>, label<span class="op">=</span><span class="st">'NJ counterfactual (PA trend applied)'</span>)</span>
<span id="cb7-303"><a href="#cb7-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-304"><a href="#cb7-304" aria-hidden="true" tabindex="-1"></a><span class="co"># Shade the DiD gap</span></span>
<span id="cb7-305"><a href="#cb7-305" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">''</span>, xy<span class="op">=</span>(<span class="dv">2</span>, nj_w2), xytext<span class="op">=</span>(<span class="dv">2</span>, nj_counterfactual),</span>
<span id="cb7-306"><a href="#cb7-306" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">'&lt;-&gt;'</span>, color<span class="op">=</span><span class="st">'#2ca02c'</span>, lw<span class="op">=</span><span class="dv">2</span>))</span>
<span id="cb7-307"><a href="#cb7-307" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">2.04</span>, (nj_w2 <span class="op">+</span> nj_counterfactual) <span class="op">/</span> <span class="dv">2</span>,</span>
<span id="cb7-308"><a href="#cb7-308" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f'DiD ≈ </span><span class="sc">{</span>did<span class="sc">:.2f}</span><span class="ss"> FTE</span><span class="ch">\n</span><span class="ss">(paper: +2.75)'</span>,</span>
<span id="cb7-309"><a href="#cb7-309" aria-hidden="true" tabindex="-1"></a>        va<span class="op">=</span><span class="st">'center'</span>, fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span><span class="st">'#2ca02c'</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb7-310"><a href="#cb7-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-311"><a href="#cb7-311" aria-hidden="true" tabindex="-1"></a><span class="co"># Labels</span></span>
<span id="cb7-312"><a href="#cb7-312" aria-hidden="true" tabindex="-1"></a>ax.set_xticks([<span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb7-313"><a href="#cb7-313" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([<span class="st">'Wave 1</span><span class="ch">\n</span><span class="st">(Before: Feb–Mar 1992)'</span>,</span>
<span id="cb7-314"><a href="#cb7-314" aria-hidden="true" tabindex="-1"></a>                     <span class="st">'Wave 2</span><span class="ch">\n</span><span class="st">(After: Nov–Dec 1992)'</span>], fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb7-315"><a href="#cb7-315" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">'Mean FTE Employment'</span>, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb7-316"><a href="#cb7-316" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"NJ vs. PA Fast Food Employment</span><span class="ch">\n</span><span class="st">Before and After NJ's Minimum Wage Increase"</span>,</span>
<span id="cb7-317"><a href="#cb7-317" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">13</span>, fontweight<span class="op">=</span><span class="st">'bold'</span>)</span>
<span id="cb7-318"><a href="#cb7-318" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="fl">0.7</span>, <span class="fl">2.5</span>)</span>
<span id="cb7-319"><a href="#cb7-319" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="bu">min</span>(pa_w2, nj_counterfactual) <span class="op">-</span> <span class="dv">2</span>, <span class="bu">max</span>(nj_w1, pa_w1) <span class="op">+</span> <span class="dv">3</span>)</span>
<span id="cb7-320"><a href="#cb7-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-321"><a href="#cb7-321" aria-hidden="true" tabindex="-1"></a><span class="co"># Annotate point values</span></span>
<span id="cb7-322"><a href="#cb7-322" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> x, y, lbl <span class="kw">in</span> [(<span class="dv">1</span>, nj_w1, <span class="ss">f'</span><span class="sc">{</span>nj_w1<span class="sc">:.1f}</span><span class="ss">'</span>), (<span class="dv">2</span>, nj_w2, <span class="ss">f'</span><span class="sc">{</span>nj_w2<span class="sc">:.1f}</span><span class="ss">'</span>),</span>
<span id="cb7-323"><a href="#cb7-323" aria-hidden="true" tabindex="-1"></a>                   (<span class="dv">1</span>, pa_w1, <span class="ss">f'</span><span class="sc">{</span>pa_w1<span class="sc">:.1f}</span><span class="ss">'</span>), (<span class="dv">2</span>, pa_w2, <span class="ss">f'</span><span class="sc">{</span>pa_w2<span class="sc">:.1f}</span><span class="ss">'</span>)]:</span>
<span id="cb7-324"><a href="#cb7-324" aria-hidden="true" tabindex="-1"></a>    ax.annotate(lbl, (x, y), textcoords<span class="op">=</span><span class="st">'offset points'</span>, xytext<span class="op">=</span>(<span class="op">-</span><span class="dv">18</span>, <span class="dv">6</span>), fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb7-325"><a href="#cb7-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-326"><a href="#cb7-326" aria-hidden="true" tabindex="-1"></a>ax.axvline(x<span class="op">=</span><span class="fl">1.5</span>, color<span class="op">=</span><span class="st">'gray'</span>, linestyle<span class="op">=</span><span class="st">':'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>, linewidth<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-327"><a href="#cb7-327" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">1.52</span>, ax.get_ylim()[<span class="dv">1</span>] <span class="op">-</span> <span class="fl">0.5</span>, <span class="st">'Minimum wage</span><span class="ch">\n</span><span class="st">increased (Apr 1992)'</span>,</span>
<span id="cb7-328"><a href="#cb7-328" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span><span class="st">'gray'</span>, va<span class="op">=</span><span class="st">'top'</span>)</span>
<span id="cb7-329"><a href="#cb7-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-330"><a href="#cb7-330" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">'lower left'</span>, fontsize<span class="op">=</span><span class="fl">9.5</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>)</span>
<span id="cb7-331"><a href="#cb7-331" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'top'</span>].set_visible(<span class="va">False</span>)</span>
<span id="cb7-332"><a href="#cb7-332" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'right'</span>].set_visible(<span class="va">False</span>)</span>
<span id="cb7-333"><a href="#cb7-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-334"><a href="#cb7-334" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-335"><a href="#cb7-335" aria-hidden="true" tabindex="-1"></a>plt.savefig(<span class="st">'parallel_trends.png'</span>, dpi<span class="op">=</span><span class="dv">150</span>, bbox_inches<span class="op">=</span><span class="st">'tight'</span>)</span>
<span id="cb7-336"><a href="#cb7-336" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb7-337"><a href="#cb7-337" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb7-338"><a href="#cb7-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-339"><a href="#cb7-339" aria-hidden="true" tabindex="-1"></a>**How to read this chart:** The blue solid line is New Jersey's actual employment trajectory. The red dashed line is Pennsylvania's. The blue dotted line is the *counterfactual* — what NJ employment would have looked like if it had simply followed Pennsylvania's trend.</span>
<span id="cb7-340"><a href="#cb7-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-341"><a href="#cb7-341" aria-hidden="true" tabindex="-1"></a>The difference between the blue solid line (what actually happened in NJ) and the blue dotted line (what the DiD framework says would have happened without the policy) is the **causal estimate** — marked in green. NJ employment fell *less* than the counterfactual predicted, implying the minimum wage had a small positive (or at worst neutral) effect on employment.</span>
<span id="cb7-342"><a href="#cb7-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-343"><a href="#cb7-343" aria-hidden="true" tabindex="-1"></a>This visualization makes the parallel trends assumption intuitive: we are betting that, without the NJ wage increase, the gap between the two lines would have stayed roughly constant. If you believe PA is a valid counterfactual for NJ — a fast food restaurant in Trenton is probably more like one in Philadelphia than one in San Francisco — then the DiD is credible.</span>
<span id="cb7-344"><a href="#cb7-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-345"><a href="#cb7-345" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-346"><a href="#cb7-346" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-347"><a href="#cb7-347" aria-hidden="true" tabindex="-1"></a><span class="fu">## Why Does DiD Enable a Causal Claim?</span></span>
<span id="cb7-348"><a href="#cb7-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-349"><a href="#cb7-349" aria-hidden="true" tabindex="-1"></a>Standard cross-sectional comparisons are plagued by selection bias: NJ and PA differ in many ways beyond their minimum wages (demographics, cost of living, labor market tightness). A naive before–after comparison in NJ alone confounds the policy effect with any other changes happening to the fast food industry over the same period (recession, changing consumer preferences, etc.).</span>
<span id="cb7-350"><a href="#cb7-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-351"><a href="#cb7-351" aria-hidden="true" tabindex="-1"></a>DiD sidesteps both problems by using two differences:</span>
<span id="cb7-352"><a href="#cb7-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-353"><a href="#cb7-353" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Cross-section:** Compare NJ to PA (removes time-invariant differences between states)</span>
<span id="cb7-354"><a href="#cb7-354" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Time series:** Compare before to after (removes any common time trends)</span>
<span id="cb7-355"><a href="#cb7-355" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-356"><a href="#cb7-356" aria-hidden="true" tabindex="-1"></a>Together, they isolate the *differential* change in NJ relative to what was happening to a plausible control group at the same time. As long as the parallel trends assumption holds — that NJ and PA would have moved together absent the policy — the DiD estimate is causal.</span>
<span id="cb7-357"><a href="#cb7-357" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-358"><a href="#cb7-358" aria-hidden="true" tabindex="-1"></a>Card and Krueger's design was also deliberately clever in its use of *neighboring* states. NJ and PA share a border, similar fast food markets, and were exposed to the same regional economic conditions in 1992, strengthening the plausibility of parallel trends.</span>
<span id="cb7-359"><a href="#cb7-359" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-360"><a href="#cb7-360" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-361"><a href="#cb7-361" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-362"><a href="#cb7-362" aria-hidden="true" tabindex="-1"></a><span class="fu">## Conclusion</span></span>
<span id="cb7-363"><a href="#cb7-363" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-364"><a href="#cb7-364" aria-hidden="true" tabindex="-1"></a>This replication confirms the main qualitative finding of Card and Krueger (1994): raising New Jersey's minimum wage did not reduce fast food employment relative to Pennsylvania. My point estimates track the paper's very closely for the pre-period descriptive statistics (PA wave-1 FTE = 23.38 vs. paper's 23.33; NJ pre-period coefficient = −3.04 vs. paper's −2.89; NJ post-period wage = \$5.08 vs. paper's ~\$5.05), and the DiD estimate (≈ {did:.2f}) is positive and in the same direction as the paper's 2.75.</span>
<span id="cb7-365"><a href="#cb7-365" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-366"><a href="#cb7-366" aria-hidden="true" tabindex="-1"></a>The modest gap in the DiD estimate — a well-documented feature of this publicly released dataset — stems from ambiguity in how wave-2 employment data was coded for stores that gave only partial interviews. This is a reminder that replication is never truly mechanical: choices about sample construction, missing data handling, and variable coding all matter, and original researchers' internal code is often irreplaceable. But the robustness of the *direction* of the finding across all reasonable coding choices is itself evidence of how solid the original result is.</span>
<span id="cb7-367"><a href="#cb7-367" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-368"><a href="#cb7-368" aria-hidden="true" tabindex="-1"></a>Card and Krueger's paper helped launch a generation of empirical labor economics built on natural experiments and quasi-experimental methods, and earned David Card the 2021 Nobel Prize in Economics. Thirty years later, the minimum wage debate is still alive — but the terms of evidence changed permanently in 1994.</span>
<span id="cb7-369"><a href="#cb7-369" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-370"><a href="#cb7-370" aria-hidden="true" tabindex="-1"></a>---</span>
<span id="cb7-371"><a href="#cb7-371" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-372"><a href="#cb7-372" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb7-373"><a href="#cb7-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-374"><a href="#cb7-374" aria-hidden="true" tabindex="-1"></a>Card, David, and Alan B. Krueger. 1994. "Minimum Wages and Employment: A Case Study of the Fast Food Industry in New Jersey and Pennsylvania." *American Economic Review* 84(4): 772–793.</span>
<span id="cb7-375"><a href="#cb7-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-376"><a href="#cb7-376" aria-hidden="true" tabindex="-1"></a>Data available at: <span class="co">[</span><span class="ot">https://davidcard.berkeley.edu/data_sets.html</span><span class="co">](https://davidcard.berkeley.edu/data_sets.html)</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>